Repository fpsim/fpsim, pull requests merged in 2023-02, with the labels that each got.

#113 Add weights to contraceptive matrices
  CHANGELOG.rst
  fpsim/locations/kenya.py
  fpsim/locations/kenya/matrices_kenya_dhs_2014_weighted.csv
  fpsim/locations/kenya/matrices_kenya_pma_2019_20_weighted.csv
  fpsim/version.py
Labels: bug

#119 Optimize birth space preferences separately for data
  CHANGELOG.rst
  fpsim/locations/data_processing/age_at_first_birth_DHS.R
  fpsim/locations/data_processing/birth_spacing.R
  fpsim/locations/kenya/afb.median.csv
  fpsim/locations/kenya/afb.table.csv
  fpsim/locations/kenya/birth_spacing_dhs.csv
  fpsim/locations/senegal/optimize-space-prefs.py
  fpsim/version.py
Labels: enhancement, calibration

#118 Ethiopia calibration
  CHANGELOG.rst
  fpsim/locations/data_processing/skyscrapers.R
  fpsim/locations/ethiopia/ethiopia_asfr.csv
  fpsim/locations/ethiopia/ethiopia_basic_dhs.yaml
  fpsim/locations/ethiopia/ethiopia_cpr.csv
  fpsim/locations/ethiopia/ethiopia_popsize.csv
  fpsim/locations/ethiopia/ethiopia_tfr.csv
  fpsim/locations/ethiopia/mix_ethiopia.csv
  fpsim/locations/ethiopia/mortality_prob_ethiopia.csv
  fpsim/locations/ethiopia/skyscraper_ethiopia_2023-01-30.csv
  fpsim/locations/ethiopia/use_ethiopia.csv
  fpsim/version.py
Labels: calibration
